# Generated by Django 4.2.4 on 2023-08-16 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('bar_code', models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_food/%Y/%m/%d')),
                ('proteins', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fats', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('kcal', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('be_confirmed', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_evop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gram', models.DecimalField(decimal_places=1, max_digits=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evop.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
