# Generated by Django 4.2.4 on 2023-08-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL category'),
        ),
    ]
