# Generated by Django 4.2.4 on 2023-08-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evop', '0005_alter_food_carbohydrates_alter_food_fats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name', 'category')},
        ),
    ]
