# Generated by Django 4.2.4 on 2023-08-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evop', '0006_alter_category_options_alter_food_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
