# Generated by Django 4.2.4 on 2023-09-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evop', '0010_alter_intake_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='be_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
