# Generated by Django 4.2.4 on 2023-09-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evop', '0012_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
