# Generated by Django 4.2.4 on 2023-09-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evop', '0013_alter_food_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='food',
            name='bar_code',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=14, null=True, unique=True),
        ),
    ]
