# Generated by Django 4.2.4 on 2023-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evop', '0014_alter_category_options_alter_food_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='bar_code',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True),
        ),
    ]
